linters-settings:
  staticcheck:
    checks:
      - "all"

linters:
  disable-all: false
  enable-all: true
  disable:
# Deprecated or auto disabled for lack of generics support
    - deadcode
    - scopelint
    - exhaustivestruct
    - maligned
    - interfacer
    - varcheck
    - golint
    - ifshort
    - structcheck
    - nosnakecase
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
# Too annoying
    - exhaustruct
